#!/system/bin/sh
sleep 1

chmod 644 /sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq
echo '520000' > /sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq
chmod 444 /sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq
